"""BasketVision Coach public API."""

from basketvision_coach.coach import CoachFeedback, ShotObservation, assess_shot
from basketvision_coach.cv_pipeline import (
    BoundingBox,
    CourtPoint,
    DetectionCandidate,
    DetectionJobSpec,
    DetectionRecord,
    InMemoryVisionStore,
    JobProgress,
    ModelSpec,
    OverlayOptions,
    PipelineResult,
    ProcessingRun,
    TrackingJobSpec,
    TrackRecord,
    VisionPipeline,
    WorkerConnections,
    WorkerRuntime,
)
from basketvision_coach.identity import (
    Correction,
    IdentityReviewService,
    PlayerStatObservation,
    RosterPlayer,
    RosterTeam,
    SpacingObservation,
    TrackIdentity,
)

__all__ = [
    "BoundingBox",
    "CoachFeedback",
    "Correction",
    "CourtPoint",
    "DetectionCandidate",
    "DetectionJobSpec",
    "DetectionRecord",
    "IdentityReviewService",
    "InMemoryVisionStore",
    "JobProgress",
    "ModelSpec",
    "OverlayOptions",
    "PipelineResult",
    "PlayerStatObservation",
    "ProcessingRun",
    "RosterPlayer",
    "RosterTeam",
    "ShotObservation",
    "SpacingObservation",
    "TrackIdentity",
    "TrackRecord",
    "TrackingJobSpec",
    "VisionPipeline",
    "WorkerConnections",
    "WorkerRuntime",
    "assess_shot",
]
